#
# --------------------------
# プロジェクト管理
# --------------------------
#
[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
let g:rooter_patterns = ['.git/', '.phpactor.yml']
'''
#
# --------------------------
# シンタックスチェック
# --------------------------
#
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
call LoadSource('default/ale.vim')
'''
#
# --------------------------
# 補完
# --------------------------
#
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''
#
# --------------------------
# スニペット
# --------------------------
#
[[plugins]]
repo = 'SirVer/ultisnips'
on_i = 1
hook_add = '''
call LoadSource('default/ultisnips.vim')
'''
[[plugins]]
repo = 'honza/vim-snippets'
#
# --------------------------
# Quickrun
# --------------------------
#
[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ['php', 'php.unit']
hook_add = '''
call LoadSource('default/quickrun.vim')
'''

#
# JSX開発
#
#
[[plugins]]
repo = 'mxw/vim-jsx'
#
# PHP開発環境
#
# https://mattn.kaoriya.net/software/lang/go/20190205190203.htm
#
[[plugins]]
repo = 'phpactor/phpactor'
build = 'composer install'
on_ft = ['php']
hook_add = '''
call LoadSource('default/phpactor.vim')
'''
[[plugins]]
repo = 'kristijanhusak/deoplete-phpactor'
on_ft = ['php']
